/** Single NAP. Footer, schema, SerpBear business name, and /kolkata all read this. */
export const LOCAL = {
  name: "The AI Workshop",
  legalName: "The AI Workshop",
  aliases: ["AI Workshop Kolkata", "AI Workshop Salt Lake", "theaiworkshop.in"] as const,
  url: "https://www.theaiworkshop.in/",
  email: "theaiworkshop.in@gmail.com",
  phoneTel: "+919830715557",
  phoneDisplay: "+91 98307 15557",
  phoneSchema: "+91-98307-15557",
  street: "Salt Lake",
  locality: "Kolkata",
  region: "West Bengal",
  postalCode: "700064",
  country: "IN",
  countryName: "India",
  neighbourhood: "Salt Lake (Bidhannagar)",
  areaLine: "Salt Lake, Kolkata, West Bengal 700064",
  lat: 22.5804,
  lng: 88.4177,
  mapsUrl: "https://maps.google.com/?q=Salt+Lake+Kolkata",
  instagram: "https://www.instagram.com/theaiworkshop.in",
  languages: ["en", "hi", "bn"] as const,
  priceRange: "₹₹",
} as const;

export const LOCAL_KEYWORDS = [
  "AI workshop Kolkata",
  "AI classes Kolkata",
  "learn AI Kolkata",
  "AI course Kolkata",
  "AI training Kolkata",
  "offline AI workshop Kolkata",
  "ChatGPT workshop Kolkata",
  "AI workshop Salt Lake",
  "AI classes Salt Lake Kolkata",
  "hands-on AI workshop Kolkata",
  "AI for beginners Kolkata",
  "Gemini workshop Kolkata",
  "AI meetup Kolkata",
  "best AI workshop Kolkata",
  "AI community Kolkata",
  "AI workshop Bidhannagar",
  "AI workshop New Town Kolkata",
  "learn ChatGPT Kolkata",
  "Sunday AI workshop Kolkata",
  "AI workshop Sector V",
] as const;
